# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Npm@1
  displayName: 'Install JsonLint'
  inputs:
    command: 'custom'
    customCommand: 'install JsonLint -g'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      files="infrastructure"
      for filepath in $files/*.json; do
          jsonlint $filepath
      done
    workingDirectory: 'modern-data-warehouse-dataops/single_tech_samples/cosmosdb'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'nparker-iache-tosako(08378850-6c96-440f-9397-b41c1a8d185c)'
    subscriptionId: '08378850-6c96-440f-9397-b41c1a8d185c'
    location: 'Australia Southeast'
    templateLocation: 'Linked artifact'
    csmFile: 'modern-data-warehouse-dataops/single_tech_samples/cosmosdb/infrastructure/azuredeploy.cosmosdb.json'
    deploymentMode: 'Validation'